const productRoutes = require("./productRoutes");
const stockoutRoutes = require("./stockoutRoutes");
const stockinRoutes = require("./stockinRoutes");
const customerRoutes = require("./customerRoutes");
const supplierRoutes = require("./supplierRoutes");
const operatorRoutes = require("./operatorRoutes");
const categoryRoutes = require("./categoryRoutes");
const authRotutes = require("./authRoutes");
const statsRoutes = require("./statsRoutes");
const backupRoutes = require("./backupRoutes");
const { isAuthenticated } = require("../../middleware/apiKeyAuth");
const router = require("express").Router();

router.use("/auth", authRotutes);
router.use("/product", isAuthenticated, productRoutes);
router.use("/stockout", isAuthenticated, stockoutRoutes);
router.use("/stockin", isAuthenticated, stockinRoutes);
router.use("/customer", isAuthenticated, customerRoutes);
router.use("/supplier", isAuthenticated, supplierRoutes);
router.use("/operator", isAuthenticated, operatorRoutes);
router.use("/category", isAuthenticated, categoryRoutes);
router.use("/stats", isAuthenticated, statsRoutes);
router.use("/backup", isAuthenticated, backupRoutes);
module.exports = router;
