models:
  - name: Product
    fields:
      name:
        type: string
      price:
        type: number
      cost_price:
        type: number
      stock_quantity:
        type: number
      low_stock_threshold:
        type: number
      category:
        ref: Category
      supplier:
        ref: Supplier
      description:
        type: text
    options:
      pagination: true
      search:
        - name
        - price

  - name: Category
    fields:
      name:
        type: string
      description:
        type: text
    options:
      pagination: false

  - name: Supplier
    fields:
      name:
        type: string
      phone:
        type: string
      email:
        type: string
      country:
        type: string
      address:
        type: string

  - name: Customer
    fields:
      name:
        type: string
      phone:
        type: string
      email:
        type: string
      address:
        type: string

  - name: Operator
    fields:
      username:
        type: string
      role:
        type: enum
        values:
          - admin
          - staff
      password:
        type: string

  - name: StockIn
    fields:
      product:
        ref: Product
      supplier:
        ref: Supplier
      quantity:
        type: number
      cost_price:
        type: number
      date:
        type: date
      note:
        type: text

  - name: StockOut
    fields:
      product:
        ref: Product
      customer:
        ref: Customer
      quantity:
        type: number
      price:
        type: number
      date:
        type: date
